server:
  port: 8080

external:
  fastapi-url: http://127.0.0.1:8000/predict

spring:
  application:
    name: weather-consume-api

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
